export enum UserStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  BLOCKED = "BLOCKED",
  SUSPENDED = "SUSPENDED",
  DEACTIVATED = "DEACTIVATED",
  PENDING_VERIFICATION = "PENDING_VERIFICATION",
  PASSWORD_EXPIRED = "PASSWORD_EXPIRED",
  LOCKED = "LOCKED",
  DELETED = "DELETED",
  EXTERNAL = "EXTERNAL",
  ARCHIVED = "ARCHIVED",
}
