name: firma_gamc
version: "3.8"
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: firma_gamc_gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - APPROVET_SERVICE_URL=http://approvet-service:3001
    networks:
      - firma_gamc_network

  approvet-service:
    build:
      context: ./approvet-service
      dockerfile: Dockerfile
    container_name: firma_gamc_approvet
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
    networks:
      - firma_gamc_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: firma_gamc_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - firma_gamc_network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: firma_gamc_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - firma_gamc_network

networks:
  firma_gamc_network:
    name: firma_gamc_network
    driver: bridge
